version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: changement du datatype pour purchase_price
        columns:
          - name: products_id
            tests:
            - unique 
            - not_null
      - name: sales
        columns:
          - name: pdt_id
          - name: orders_id
        identifier: raw_gz_sales
        description: rename pdt_id en product_id
        tests:
        - unique:
            column_name: "(orders_id || '-' || pdt_id)"
      - name : ship
        identifier: raw_gz_ship
        description: suppression de la colonne shipping_fee_1 et chgt datatype de ship_cost
        columns:
          - name: orders_id
            tests:
             - unique
             - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: rename camPNG to campaign_name & changer le datatype du ads_cost en float64
      - name: bing
        identifier: raw_gz_bing
        description: rename camPNG to campaign_name & changer le datatype du ads_cost en float64
        
      - name: criteo
        identifier: raw_gz_criteo
        description: rename camPNG to campaign_name & changer le datatype du ads_cost en float64
      - name: facebook
        identifier: raw_gz_facebook
        description: rename camPNG to campaign_name & changer le datatype du ads_cost en float64

models:
  - name: int_campaigns
    description: test de primary key
    columns:
      - name: date_date
      - name: campaign_key
    tests:
      - unique:
           column_name: "(date_date || '-' || campaign_key)"


